# Build
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Dependencies
COPY go.mod go.sum ./
RUN go mod download

# Source code
COPY internal/ ./internal
COPY cmd/ ./cmd
COPY databases/ ./databases

# Compilation
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o worker-analysis ./cmd/worker-analysis

# Bioinformatics
FROM mambaorg/micromamba:latest

# System dependencies
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    procps \
    libgomp1 \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Back to Mamba user to install tools
USER $MAMBA_USER

# Pipeline via Bioconda
RUN micromamba install -y -n base -c bioconda -c conda-forge \
    "fastqc=0.12.1" \
    unicycler \
    "spades=4.3.0" \
    "prokka=1.14.6" \
    "checkm2" \
    "kraken2=2.17.1" \
    "fastani=1.34" \
    "abricate=1.4.0" \
    "mlst" \
    "blast=2.17.0" \
    "parallel=20241122" \
    && micromamba clean --all --yes

WORKDIR /app

# Compiled binary
# Copy Go binary from builder into the bioinformatics environment
COPY --from=builder --chown=$MAMBA_USER:$MAMBA_USER /app/worker-analysis .
RUN chmod +x worker-analysis

# Data folders needed at runtime
COPY --from=builder --chown=$MAMBA_USER:$MAMBA_USER /app/databases ./databases
COPY --from=builder --chown=$MAMBA_USER:$MAMBA_USER /app/internal/translation/active ./internal/translation/active

# Required by micromamba base active
ARG MAMBA_DOCKERFILE_ACTIVATE=1

CMD ["./worker-analysis"]