package services

import "errors"

// Generic errors
var ErrNotFound = errors.New("record not found")
var ErrInternal = errors.New("internal system error")
var ErrConflict = errors.New("record already exists")
var ErrUnauthorized = errors.New("unauthorized")

// Specific errors
var ErrInvalidCountryCode = errors.New("invalid country code")
var ErrConflictEmail = errors.New("email already exists")
var ErrConflictUsername = errors.New("username already exists")
var ErrEmailMismatch = errors.New("emails must match")
var ErrPasswordMismatch = errors.New("passwords must match")
var ErrInvalidCredentials = errors.New("invalid credentials")
var ErrDisabledUser = errors.New("disabled user")
var ErrOriginNotFound = errors.New("origin not found")
var ErrUserNotFound = errors.New("user not found")
var ErrSampleSourceNotFound = errors.New("sample source not found")
var ErrMicroorganismNotFound = errors.New("microorganism not found")
var ErrSequencerNotFound = errors.New("sequencer not found")
var ErrLaboratoryNotFound = errors.New("laboratory not found")
var ErrHealthServiceNotFound = errors.New("health service not found")
var ErrMissingFiles = errors.New("missing files")
var ErrMissingFastq1 = errors.New("missing fastq1 file")
var ErrMissingFastq2 = errors.New("missing fastq2 file")
var ErrCreateFolder = errors.New("cannot create folder")
var ErrDeleteRunningAnalysis = errors.New("cannot delete analysis")
var ErrSampleNotFound = errors.New("sample not found")
var ErrExceededDownloadLimit = errors.New("exceeded download limit")
var ErrTicketAlreadyResolvedStatus = errors.New("ticket already resolved")
var ErrTicketIsNotOpen = errors.New("ticket in progress or resolved")
var ErrDeleteActiveTicket = errors.New("cannot delete active ticket")
var ErrInvalidToken = errors.New("invalid token")
var ErrExpiredToken = errors.New("token is expired")
var ErrAnalysisRun = errors.New("analysis failed")
var ErrFastQC = errors.New("analysis failed during the FastQC step")
var ErrUnicycler = errors.New("analysis failed during the Unicycler step")
var ErrProkka = errors.New("analysis failed during the Prokka step")
var ErrCheckM = errors.New("analysis failed during the CheckM step")
var ErrKraken2 = errors.New("analysis failed during the Kraken2 step")
var ErrSpecies = errors.New("analysis failed during the Species step")
var ErrAbricate = errors.New("analysis failed during the Abricate step")
var ErrPrepareFolders = errors.New("analysis failed during folder preparation")
var ErrUnknownAnalysisType = errors.New("unknown analysis type")
